repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: \.pyi?$
        exclude: \.git  | \.hg  | \.mypy_cache| \.tox| \.venv| _build| buck-out| build| dist| jsons.py| alembic
        args: [--line-length=80, --check, --verbose]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-requests"
          - "pydantic"
          - "sqlalchemy-stubs"
        args:
          - --no-strict-optional
          - --ignore-missing-imports
        exclude: alembic
