"""sqlmodel

Revision ID: ddfb269c7ea5
Revises: 
Create Date: 2022-03-15 17:05:59.616786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ddfb269c7ea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freshdeskticketmodel', sa.Column('fwd_emails', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('reply_cc_emails', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('ticket_cc_emails', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('fr_escalated', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('spam', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('email_config_id', sa.Integer(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('requester_id', sa.Integer(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('responder_id', sa.Integer(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('source', sa.Integer(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('association_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('support_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('to_emails', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('due_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('fr_due_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('is_escalated', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('associated_tickets_count', sa.Integer(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('nr_due_by', sa.DateTime(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('nr_escalated', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('cf_partner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('cf_information_not_provided_by_requester', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('cf_applicant_did_not_respond', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('cf_duplicate_request', sa.Boolean(), nullable=False))
    op.add_column('freshdeskticketmodel', sa.Column('cf_follow_up_date', sa.DateTime(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('cf_compliance_outreach', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('cf_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('freshdeskticketmodel', sa.Column('cf_turn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('freshdeskticketmodel', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_freshdeskticketmodel_id', table_name='freshdeskticketmodel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_freshdeskticketmodel_id', 'freshdeskticketmodel', ['id'], unique=False)
    op.alter_column('freshdeskticketmodel', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('freshdeskticketmodel', 'cf_turn_id')
    op.drop_column('freshdeskticketmodel', 'cf_first_name')
    op.drop_column('freshdeskticketmodel', 'cf_compliance_outreach')
    op.drop_column('freshdeskticketmodel', 'cf_follow_up_date')
    op.drop_column('freshdeskticketmodel', 'cf_duplicate_request')
    op.drop_column('freshdeskticketmodel', 'cf_applicant_did_not_respond')
    op.drop_column('freshdeskticketmodel', 'cf_information_not_provided_by_requester')
    op.drop_column('freshdeskticketmodel', 'cf_partner_name')
    op.drop_column('freshdeskticketmodel', 'nr_escalated')
    op.drop_column('freshdeskticketmodel', 'nr_due_by')
    op.drop_column('freshdeskticketmodel', 'tags')
    op.drop_column('freshdeskticketmodel', 'associated_tickets_count')
    op.drop_column('freshdeskticketmodel', 'updated_at')
    op.drop_column('freshdeskticketmodel', 'created_at')
    op.drop_column('freshdeskticketmodel', 'is_escalated')
    op.drop_column('freshdeskticketmodel', 'fr_due_by')
    op.drop_column('freshdeskticketmodel', 'due_by')
    op.drop_column('freshdeskticketmodel', 'type')
    op.drop_column('freshdeskticketmodel', 'product_id')
    op.drop_column('freshdeskticketmodel', 'to_emails')
    op.drop_column('freshdeskticketmodel', 'support_email')
    op.drop_column('freshdeskticketmodel', 'association_type')
    op.drop_column('freshdeskticketmodel', 'subject')
    op.drop_column('freshdeskticketmodel', 'status')
    op.drop_column('freshdeskticketmodel', 'company_id')
    op.drop_column('freshdeskticketmodel', 'source')
    op.drop_column('freshdeskticketmodel', 'responder_id')
    op.drop_column('freshdeskticketmodel', 'requester_id')
    op.drop_column('freshdeskticketmodel', 'priority')
    op.drop_column('freshdeskticketmodel', 'group_id')
    op.drop_column('freshdeskticketmodel', 'email_config_id')
    op.drop_column('freshdeskticketmodel', 'spam')
    op.drop_column('freshdeskticketmodel', 'fr_escalated')
    op.drop_column('freshdeskticketmodel', 'ticket_cc_emails')
    op.drop_column('freshdeskticketmodel', 'reply_cc_emails')
    op.drop_column('freshdeskticketmodel', 'fwd_emails')
    # ### end Alembic commands ###
